name: Greeting Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true
        default: 'World'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          sleep 50
          echo "Hello from PyCon LT 2024!!!"
