name: Greeting Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true
        default: 'World'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          sleep 10
          echo "     <3      <3  "
          echo "    <3  <3 <3  <3"
          echo "  <3    <3    <3"
          echo "   <3         <3"   PyCon LT 2024!
          echo "     <3     <3"
          echo "       <3  <3"
          echo "         <3"
